<div class="page">
    <div class="svg" style="margin-left: auto; margin-right:auto; display: none; position: relative; opacity: 100%; width: 100px; height: 100px;">
        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; background: transparent; display: block; shape-rendering: auto;" width="calc(100% - 30px)" height="calc(100% - 30px)" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
            <circle cx="50" cy="50" fill="none" stroke="#1d0e0b" stroke-width="10" r="35" stroke-dasharray="164.93361431346415 56.97787143782138">
                <animateTransform attributeName="transform" type="rotate" repeatCount="indefinite" dur="1s" values="0 50 50;360 50 50" keyTimes="0;1"></animateTransform>
            </circle>
            <!-- [ldio] generated by https://loading.io/ -->
        </svg>
    </div>
    
    <div class="table-container">
        <div class="row hidden"></div>
        <h1 class="mb-4">Daftar Permohonan Tanda Tangan</h1>
        <table class="table table-bordered data-striped">
            <thead>
                <tr>
                    <td>No.</td>
                    <td>Waktu</td>
                    <td>Status</td>
                    <td>Keterangan</td>
                    <td>Tindakan</td>
                </tr>
            </thead>
            <tbody>
                
            </tbody>
        </table>
        <div class="img-container"></div>
    </div>
</div>

<script>

    function listSignature() {
        $('table').DataTable({
            ajax: '{{route("get-list-permohonan")}}',
            serverSide: true,
            processing: true,
            searching: false,
            // scrollX: true,
            language: {
                url: "https://cdn.datatables.net/plug-ins/1.10.9/i18n/Indonesian.json"
            },
            columnDefs: [
                { width: '5%', targets: 0 },
                { width: '15%', targets: 1 },
                { width: '20%', targets: 2 },
                { width: '30%', targets: 3 },
                { width: '30%', targets: 4 },
            ],
            columns: [
                {
                    data: '',
                    render: (data, type, row, meta) => {
                        return meta.row + meta.settings._iDisplayStart + 1
                    }
                },
                {
                    data: null,
                    render: function(data, type, full, meta) {
                        return `
                        <div style="word-break: break-all">
                            ${data.created_at}
                        </div>
                        `
                    }
                },
                {
                    data: null,
                    render: function(data, type, full, meta) {
                        if(data.signature_detail.signature == null){
                            return `
                                <div class="text-danger"><b>Belum Direspon</b></div>
                            `
                        }else if (data.signature_detail.signature == "rejected"){
                            return `
                                <div class="text-danger"><b>Ditolak</b></div>
                            `
                        }else {
                            return `
                                <div class="text-success"><b>Disetujui</b></div>
                            `
                        }
                    }
                },
                {
                    data: null,
                    render: function(data, type, full, meta) {
                        return `
                            ${data.signature_detail.note}
                        `
                    }
                },
                {
                    data: null,
                    render: function(data, type, full, meta) {
                        let action = `
                        <div id="loading${meta.row + meta.settings._iDisplayStart + 1}" style="display: none">
                            <div class="svg" style="margin-left: auto; margin-right:auto; display: block; position: relative; opacity: 100%; width: 100px; height: 100px;">
                                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; background: transparent; display: block; shape-rendering: auto;" width="calc(100% - 30px)" height="calc(100% - 30px)" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
                                    <circle cx="50" cy="50" fill="none" stroke="#1d0e0b" stroke-width="10" r="35" stroke-dasharray="164.93361431346415 56.97787143782138">
                                        <animateTransform attributeName="transform" type="rotate" repeatCount="indefinite" dur="1s" values="0 50 50;360 50 50" keyTimes="0;1"></animateTransform>
                                    </circle>
                                    <!-- [ldio] generated by https://loading.io/ -->
                                </svg>
                            </div>
                        </div>
                        <div id="downloader${meta.row + meta.settings._iDisplayStart + 1}" style="display: flex">
                            <button class="btn btn-primary" type="button" onclick="downloadSignature(\'${data.signature_detail.hash}\', ${meta.row + meta.settings._iDisplayStart + 1})">
                                <i class="mai mai-image"></i>
                                Unduh Tanda Tangan
                            </button>
                        </div>
                        `
                        if (data.signature_detail.signature == null || data.signature_detail.signature == "rejected") {
                            action = ''
                        }
                        return action
                    }
                }
            ]
        })
    }
    listSignature()

    function downloadSignature(hash, count) {
        $.ajax({
            url: `{{ url('/get-img') }}`,
            type: "POST",
            data: {
                _token: '{{ csrf_token() }}',
                hash: hash
            },
            beforeSend: () => {
                document.querySelector(`#downloader${count}`).style.display = "none"
                document.querySelector(`#loading${count}`).style.display = "flex"
            },
            success: (res) => {
                document.querySelector(".img-container").innerHTML = `
                    <img id="sign-preview" src="" style="display: none; max-width: 700px; max-height:700" alt="Tanda Tangan Preview">
                    <div id="qrcode" style="display: none"></div>
                    <canvas id="sign-img" style="display: none" width="1200px" height="700px"></canvas>
                `
                const image = document.querySelector('#sign-preview')
                image.src = "{{ asset('storage') }}/"+res.signature
                const canvas = document.querySelector("#sign-img")
                const ctx = canvas.getContext("2d")
                
                setTimeout(() => {
                    const width = image.width
                    const height = image.height
                    let rectangleSide = 200
                    if (width > height) {
                        rectangleSide = height
                    } else{
                        rectangleSide = width
                    }
                    ctx.drawImage( image, 0, 0, 700, image.height * (700/image.width))
                    const qrcode = new QRCode("qrcode", {
                        text: hash,
                        width: 300,
                        height: 300,
                        colorDark : "#000000",
                        colorLight : "#ffffff",
                        correctLevel : QRCode.CorrectLevel.L
                    })
                    console.log(image.width, image.height)
                    document.querySelector(`#loading${count}`).style.display = "none"
                    document.querySelector(`#downloader${count}`).style.display = "flex"
                    setTimeout(() => {
                        ctx.drawImage( document.querySelector('#qrcode img'), 700, rectangleSide * 0.1, 300, 300)
                        const data = canvas.toDataURL("image/png")
                        // Create a link
                        const aDownloadLink = document.createElement('a')
                        // Add the name of the file to the link
                        aDownloadLink.download = 'signature.png'
                        // Attach the data to the link
                        aDownloadLink.href = data
                        // Get the code to click the download link
                        aDownloadLink.click()
                    }, 500)
                }, 500)
            }
        })
    }

    function listenerAction() {
        document.querySelector('.table-container').style.display = "none"
        setTimeout(() => {
            document.querySelector('.svg').style.display = "block"
            document.querySelectorAll('.nav-item')[0].classList.add('active')
            document.querySelectorAll('.nav-item')[1].classList.remove('active')
            $.ajax({
                url: "{{ route('get-home') }}",
                type: "GET",
                success: (res) => {
                    $('#main').html(res)
                }
            })
        }, 100)
        document.querySelectorAll('.nav-item')[0].removeEventListener("click", listenerAction)
    }

    document.querySelectorAll('.nav-item')[0].addEventListener("click", listenerAction)
</script>