<div class="page">
    <div class="svg" style="margin-left: auto; margin-right:auto; display: none; position: relative; opacity: 100%; width: 100px; height: 100px;">
        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; background: transparent; display: block; shape-rendering: auto;" width="calc(100% - 30px)" height="calc(100% - 30px)" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
            <circle cx="50" cy="50" fill="none" stroke="#1d0e0b" stroke-width="10" r="35" stroke-dasharray="164.93361431346415 56.97787143782138">
                <animateTransform attributeName="transform" type="rotate" repeatCount="indefinite" dur="1s" values="0 50 50;360 50 50" keyTimes="0;1"></animateTransform>
            </circle>
            <!-- [ldio] generated by https://loading.io/ -->
        </svg>
    </div>
    
    <div class="table-container">
        <div class="row hidden"></div>
        <h1 class="mb-4">Daftar Permohonan Tanda Tangan</h1>
        <table class="table table-bordered data-striped">
            <thead>
                <tr>
                    <td>No.</td>
                    <td>Waktu</td>
                    <td>Status</td>
                    <td>Keterangan</td>
                    <td>Tindakan</td>
                </tr>
            </thead>
            <tbody>
                
            </tbody>
        </table>
        <img src="" style="display: none; max-width: 700px; max-height:700" alt="Tanda Tangan Preview">
        <div id="qrcode"></div>
        <canvas width="1200" height="1200"></canvas>
    </div>
</div>

<script>

    function listSignature() {
        $('table').DataTable({
            ajax: '{{route("get-list-permohonan")}}',
            serverSide: true,
            processing: true,
            searching: false,
            // scrollX: true,
            language: {
                url: "https://cdn.datatables.net/plug-ins/1.10.9/i18n/Indonesian.json"
            },
            columnDefs: [
                { width: '5%', targets: 0 },
                { width: '15%', targets: 1 },
                { width: '20%', targets: 2 },
                { width: '30%', targets: 3 },
                { width: '30%', targets: 4 },
            ],
            columns: [
                {
                    data: '',
                    render: (data, type, row, meta) => {
                        return meta.row + meta.settings._iDisplayStart + 1
                    }
                },
                {
                    data: null,
                    render: function(data, type, full, meta) {
                        return `
                        <div style="word-break: break-all">
                            ${data.created_at}
                        </div>
                        `
                    }
                },
                {
                    data: null,
                    render: function(data, type, full, meta) {
                        if (data.signature_detail.signature != "rejected") {
                            return `
                                <div class="text-success"><b>Disetujui</b></div>
                            `
                        }else{
                            return `
                                <div class="text-danger"><b>Ditolak</b></div>
                            `
                        }
                    }
                },
                {
                    data: null,
                    render: function(data, type, full, meta) {
                        return `
                            ${data.signature_detail.note}
                        `
                    }
                },
                {
                    data: null,
                    render: function(data, type, full, meta) {
                        let action = `
                        <div id="loading${meta.row + meta.settings._iDisplayStart + 1}" style="display: none">
                            <div class="svg" style="margin-left: auto; margin-right:auto; display: block; position: relative; opacity: 100%; width: 100px; height: 100px;">
                                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; background: transparent; display: block; shape-rendering: auto;" width="calc(100% - 30px)" height="calc(100% - 30px)" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
                                    <circle cx="50" cy="50" fill="none" stroke="#1d0e0b" stroke-width="10" r="35" stroke-dasharray="164.93361431346415 56.97787143782138">
                                        <animateTransform attributeName="transform" type="rotate" repeatCount="indefinite" dur="1s" values="0 50 50;360 50 50" keyTimes="0;1"></animateTransform>
                                    </circle>
                                    <!-- [ldio] generated by https://loading.io/ -->
                                </svg>
                            </div>
                        </div>
                        <div id="downloader${meta.row + meta.settings._iDisplayStart + 1}" style="display: flex">
                            <button class="btn btn-primary" type="button" onclick="downloadSignature(\'${data.signature_detail.hash}\', ${meta.row + meta.settings._iDisplayStart + 1})">
                                <i class="mai mai-image"></i>
                                Unduh Tanda Tangan
                            </button>
                        </div>
                        `
                        return action
                    }
                }
            ]
        })
    }
    listSignature()

    function downloadSignature(hash, count) {
        const image = document.querySelector('img')
        $.ajax({
            url: `{{ url('/get-img') }}/${hash}`,
            type: "GET",
            beforeSend: () => {
                document.querySelector(`#downloader${count}`).style.display = "none";
                document.querySelector(`#loading${count}`).style.display = "flex";
            },
            success: (res) => {
                document.querySelector(`#loading${count}`).style.display = "none";
                document.querySelector(`#downloader${count}`).style.display = "flex";
                // image.src = signature
                // const canvas = document.querySelector("canvas")
                // const ctx = canvas.getContext("2d");
                console.log(res)
            }
        })
    }

    function listenerAction() {
        document.querySelector('.table-container').style.display = "none"
        setTimeout(() => {
            document.querySelector('.svg').style.display = "block"
            document.querySelectorAll('.nav-item')[0].classList.add('active')
            document.querySelectorAll('.nav-item')[1].classList.remove('active')
            $.ajax({
                url: "{{ route('get-home') }}",
                type: "GET",
                success: (res) => {
                    $('#main').html(res)
                }
            })
        }, 100);
        document.querySelectorAll('.nav-item')[0].removeEventListener("click", listenerAction)
    }

    document.querySelectorAll('.nav-item')[0].addEventListener("click", listenerAction)
</script>